version: '3.7'
networks: 
  nlw-network:
    name: nlw-network
    driver: bridge

services: 
  nlw-server:
    build: .
    volumes: 
      - .:/home/server
    ports: 
      - 3333:3333
    container_name: nlw-server
    command: ['yarn', 'dev']
    depends_on: 
      - nlw-db
    links: 
      - nlw-db
    env_file: 
      - .env
    networks:
      - nlw-network
  nlw-db:
    image:  postgres:alpine
    restart: always
    container_name: nlw-db
    ports:
      - 25432:5432
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    networks:
      - nlw-network